=== chenzhen10/jwdtask3/Unknown/out/artifacts/web_war_exploded/WEB-INF/classes/by/epam/kimbar/view/Menu.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://epamtr.com/Menu"
        xmlns:menu="http://epamtr.com/Menu"
        elementFormDefault="qualified">


    <element name="menu" type="menu:menus"/>

    <complexType name="menus">
        <sequence>
            <element name="cold_snack" type="menu:cold_d" maxOccurs="unbounded"/>
            <element name="hot_snack" type="menu:hot_d" maxOccurs="unbounded"/>
            <element name="breakfast" type="menu:breakfast" maxOccurs="unbounded"/>
        </sequence>
    </complexType>


    <complexType name="cold_d">
        <sequence>
            <element name="photo" type="string"/>
            <element name="name">
                <simpleType>
                    <restriction base="string">
                        <maxLength value="50"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="description" type="string" minOccurs="0"/>
            <element name="opt_descriptions" type="menu:optional_description" minOccurs="0"/>
            <element name="portion" type="string"/>
            <element name="price" type="double"  minOccurs="0"/>
        </sequence>
        <attribute name="id" use="required" type="ID"/>
    </complexType>


    <complexType name="hot_d">
        <sequence>
            <element name="photo" type="string"/>
            <element name="name">
                <simpleType>
                    <restriction base="string">
                        <maxLength value="50"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="description" type="string" minOccurs="0"/>
            <element name="opt_descriptions" type="menu:optional_description" minOccurs="0"/>
            <element name="portion" type="string"/>
            <element name="price" type="double"  minOccurs="0"/>
        </sequence>
        <attribute name="id" use="required" type="ID"/>
    </complexType>


    <complexType name="breakfast">
        <sequence>
            <element name="photo" type="string"/>
            <element name="name">
                <simpleType>
                    <restriction base="string">
                        <maxLength value="50"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="description" type="string" minOccurs="0"/>
            <element name="opt_descriptions" type="menu:optional_description" minOccurs="0"/>
            <element name="portion" type="string"/>
            <element name="price" type="double"  minOccurs="0"/>
        </sequence>
        <attribute name="id" use="required" type="ID"/>
    </complexType>


    <complexType name="optional_description">
        <sequence>
            <element name="desc_of_the_addition" maxOccurs="unbounded">
                <complexType>
                    <sequence>
                        <element name="opt_description" type="string" />
                        <element name="portion" type="string" minOccurs="0"/>
                        <element name="price" type="double"  minOccurs="0" />
                    </sequence>
                </complexType>
            </element>
        </sequence>
    </complexType>

</schema>

=== chenzhen10/jwdtask3/Unknown/out/artifacts/web_war_exploded/WEB-INF/classes/by/epam/kimbar/view/Menu.xml
<?xml version="1.0" encoding="UTF-8" ?>
<menu xmlns="http://epamtr.com/Menu"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://epamtr.com/Menu ../../../../../resources/ Menu.xsd">


    <cold_snack id="c1">
        <photo>E:\asort.jpg</photo>
        <name>Ассорти рыбное</name>
        <description>Слабосоленная форель,семга</description>
        <portion>100/20/15</portion>
    </cold_snack>

    <cold_snack id="c2">
        <photo>E:\tar.jpg</photo>
        <name>Тарталетки с красной икрой</name>
        <description>Тарталетки с красной икрой</description>
        <portion>60/50</portion>
    </cold_snack>

    <cold_snack id="c3">
        <photo>E:\zakus.jpg</photo>
        <name>Закуска по-русски</name>
        <description>Кусочки атлантической сельди с отварным картофелем,луком,лимоном и зеленью</description>
        <portion>70/50/2/10</portion>
    </cold_snack>

    <hot_snack id="h1">
        <photo>E:\lobio.jpg</photo>
        <name>Лобио с шампиньонами</name>
        <description>Лобио с шампиньонами и грецкими орехами</description>
        <portion>150/5</portion>
        <price>105</price>
    </hot_snack>

    <hot_snack id="h2">
        <photo>E:\julien.jpg</photo>
        <name>Жульен</name>
       <opt_descriptions>
           <desc_of_the_addition>
               <opt_description>1. с курицей</opt_description>
               <price>145</price>
           </desc_of_the_addition>
           <desc_of_the_addition>
               <opt_description>2. с грибами</opt_description>
               <price>155</price>
           </desc_of_the_addition>
       </opt_descriptions>
        <portion>120/1</portion>
    </hot_snack>

    <hot_snack id="h3">
        <photo>E:\ahtamar.jpg</photo>
        <name>Ахтамар мясной</name>
        <description>Колбаса,ветчина,буженина,сыр,запеченыне на мангале в лаваше</description>
        <portion>1 шт.</portion>
        <price>165</price>
    </hot_snack>


    <breakfast id="b1">
        <photo>E:\glazun.jpg</photo>
        <name>Глазунья</name>
        <description>2 яйца</description>
        <opt_descriptions>
            <desc_of_the_addition>
                <opt_description>1.ветчина</opt_description>
            </desc_of_the_addition>
            <desc_of_the_addition>
                <opt_description>2.сыр</opt_description>
            </desc_of_the_addition>
            <desc_of_the_addition>
                <opt_description>3.помидоры</opt_description>
            </desc_of_the_addition>
        </opt_descriptions>
        <portion>150</portion>
    </breakfast>

    <breakfast id="b2">
        <photo>E:\oml.jpg</photo>
        <name>Омлет</name>
        <portion>100</portion>
    </breakfast>

    <breakfast id="b3">
        <photo>E:\blin.jpg</photo>
        <name>Блинчики с мясом</name>
        <description>Жаренные блинчики с мясом</description>
        <portion>150</portion>
    </breakfast>


</menu>

=== chenzhen10/jwdtask3/Unknown/out/production/Unknown/by/epam/kimbar/resources/Menu.xml
<?xml version="1.0" encoding="UTF-8" ?>
<menu xmlns="http://epamtr.com/Menu"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://epamtr.com/Menu Menu.xsd">


    <cold_snack id="c1">
        <photo>asdasdasd.ru</photo>
        <name>Ассорти рыбное</name>
        <description>Слабосоленная форель,семга</description>
        <portion>100/20/15</portion>
        <price>0.0</price>
    </cold_snack>

    <cold_snack id="c2">
        <photo>asdfafafdaf.com</photo>
        <name>Тарталетки с красной икрой</name>
        <description>Тарталетки с красной икрой</description>
        <portion>60/50</portion>
        <price>0.0</price>
    </cold_snack>

    <hot_snack id="h1">
        <photo>afafasdfasd.by</photo>
        <name>Лобио с шампиньонами</name>
        <description>Лобио с шампиньонами и грецкими орехами</description>
        <portion>150/5</portion>
        <price>105</price>
    </hot_snack>


    <breakfast id="b1">
        <photo>afadfadf.org</photo>
        <name>Глазунья</name>
        <description>2 яйца</description>
        <opt_descriptions>
            <desc_of_the_addition>
                <opt_description>1.ветчина</opt_description>
                <price>1</price>
            </desc_of_the_addition>
            <desc_of_the_addition>
                <opt_description>2.сыр</opt_description>
                <price>0</price>
            </desc_of_the_addition>
            <desc_of_the_addition>
                <opt_description>3.помидоры</opt_description>
                <price>0</price>
            </desc_of_the_addition>
        </opt_descriptions>
        <portion>150</portion>
        <price>0.0</price>
    </breakfast>


</menu>
